name = "cardanosolutions/proxy-dreps"
version = "0.0.0"
compiler = "v1.1.1"
plutus = "v3"
license = "MPL-2.0"
description = "Aiken contracts for project 'cardanosolutions/proxy-dreps'"

[repository]
user = "cardanosolutions"
project = "proxy-dreps"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.0.0"
source = "github"

[[dependencies]]
name = "KtorZ/aicone"
version = "a9ae9ef8b6bdb183ea020ea97f6b648f9343924e"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "v2"
source = "github"

[config.default]
threshold = 1 # How many administrors signatories are required to approve actions

# List of administators (verification key hashes)
[[config.default.administrators]]
bytes = "00000000000000000000000000000000000000000000000000000000"
encoding = "base16"

[[config.default.administrators]]
bytes = "00000000000000000000000000000000000000000000000000000001"
encoding = "base16"
