name = "cardanosolutions/proxy-dreps"
version = "0.0.0"
compiler = "v1.1.2"
plutus = "v3"
license = "MPL-2.0"
description = "Aiken contracts for project 'cardanosolutions/proxy-dreps'"

[repository]
user = "cardanosolutions"
project = "proxy-dreps"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[[dependencies]]
name = "KtorZ/aicone"
version = "a9ae9ef8b6bdb183ea020ea97f6b648f9343924e"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "v2"
source = "github"

[config.default]
quorum = 1 # How many administrators signatories are required to approve actions

# List of administrators (verification key hashes)
[[config.default.administrators]]
bytes = "491512406d99b03de5fa4d03ddd2b7f047eeb6681731916fb803f23d"
encoding = "base16"
